-- c## 없이 계정 생성
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- CREATE USER 계정명 IDENTIFIED BY 비밀번호;
CREATE USER HR IDENTIFIED BY 123456;

-- ALTER USER 계정명 DEFAULT TABLESPACE users;
ALTER USER HR DEFAULT TABLESPACE users;

-- ALTER USER 계정명 QUOTA UNLIMIED ON 테이블스페이스;
ALTER USER HR QUOTA UNLIMITED ON users;

-- GRANT 권한명1, 권한명2 TO 계정명;
GRANT connect, resource TO HR;